const cache = new Map();

function getCached(selector, multi = false) {
  if (cache.has(selector)) return cache.get(selector);
  const el = multi ? document.querySelectorAll(selector) : document.querySelector(selector);
  if (el && (multi ? el.length > 0 : true)) {
    cache.set(selector, el);
  }
  return el;
}

export const refs = {
  get authView() { return getCached("#authView"); },
  get homeView() { return getCached("#homeView"); },
  get studioView() { return getCached("#studioView"); },
  get toolStrip() { return getCached("#toolStrip"); },
  get studioLayout() { return getCached("#studioLayout"); },
  get projectGrid() { return getCached("#projectGrid"); },
  get newProjectBtn() { return getCached("#newProjectBtn"); },
  get goHomeBtn() { return getCached("#goHomeBtn"); },
  get saveBadge() { return getCached("#saveBadge"); },
  get titleInput() { return getCached("#titleInput"); },
  get authorInput() { return getCached("#authorInput"); },
  get contactInput() { return getCached("#contactInput"); },
  get companyInput() { return getCached("#companyInput"); },
  get detailsInput() { return getCached("#detailsInput"); },
  get loglineInput() { return getCached("#loglineInput"); },
  get activeModeLabel() { return getCached("#activeModeLabel"); },
  get suggestionTray() { return getCached("#suggestionTray"); },
  get suggestionTitle() { return getCached("#suggestionTitle"); },
  get suggestionList() { return getCached("#suggestionList"); },
  get autoCapsToggle() { return getCached("#autoCapsToggle"); },
  get autoNumberToggle() { return getCached("#autoNumberToggle"); },
  get bgAnimationToggle() { return getCached("#bgAnimationToggle"); },
  get typewriterToggle() { return getCached("#typewriterToggle"); },
  get aiAssistToggle() { return getCached("#aiAssistToggle"); },
  get grammarCheckToggle() { return getCached("#grammarCheckToggle"); },
  get aiPanel() { return getCached("#aiPanel"); },
  get aiSuggestBtn() { return getCached("#aiSuggestBtn"); },
  get saveBtn() { return getCached("#saveBtn"); },
  get exportTxtBtn() { return getCached("#exportTxtBtn"); },
  get exportJsonBtn() { return getCached("#exportJsonBtn"); },
  get exportWordBtn() { return getCached("#exportWordBtn"); },
  get exportPdfBtn() { return getCached("#exportPdfBtn"); },
  get fileInput() { return getCached("#fileInput"); },
  get helpBtn() { return getCached("#helpBtn"); },
  get helpDialog() { return getCached("#helpDialog"); },
  get leftPane() { return getCached("#leftPane"); },
  get rightPane() { return getCached("#rightPane"); },
  get leftPaneBody() { return getCached("#leftPaneBody"); },
  get leftPaneBlockControls() { return getCached("#leftPaneBlockControls"); },
  get leftPaneEmptyState() { return getCached("#leftPaneEmptyState"); },
  get rightPaneBody() { return getCached("#rightPaneBody"); },
  get leftRailToggle() { return getCached("#leftRailToggle"); },
  get rightRailToggle() { return getCached("#rightRailToggle"); },
  get toolStripToggle() { return getCached("#toolStripToggle"); },
  get leftPaneSectionToggle() { return getCached("#leftPaneSectionToggle"); },
  get rightPaneSectionToggle() { return getCached("#rightPaneSectionToggle"); },
  get leftResize() { return getCached("#leftResize"); },
  get rightResize() { return getCached("#rightResize"); },
  get screenplayEditor() { return getCached("#screenplayEditor"); },
  get coverPreview() { return getCached("#coverPreview"); },
  get preview() { return getCached("#preview"); },
  get sceneList() { return getCached("#sceneList"); },
  get characterList() { return getCached("#characterList"); },
  get sceneCount() { return getCached("#sceneCount"); },
  get wordCount() { return getCached("#wordCount"); },
  get pageCount() { return getCached("#pageCount"); },
  get characterCount() { return getCached("#characterCount"); },
  get noteCount() { return getCached("#noteCount"); },
  get duplicateProjectBtn() { return getCached("#duplicateProjectBtn"); },
  get loadSampleBtn() { return getCached("#loadSampleBtn"); },
  get deleteProjectBtn() { return getCached("#deleteProjectBtn"); },
  get homeRecentProjects() { return getCached("#homeRecentProjects"); },
  get studioRecentProjects() { return getCached("#studioRecentProjects"); },
  get menuTriggers() { return getCached("[data-menu-trigger]", true); },
  get themeButtons() { return getCached("[data-theme-value]", true); },
  get languageButtons() { return getCached("[data-language-value]", true); },
  get writingLanguageButtons() { return getCached("[data-writing-language-value]", true); }
  };
